banner_delay:
  type: integer
  default: 6000
banner_outlet:
  default: "above-main-container"
banners:
  type: objects
  refresh: true
  default: []
  schema:
    name: banner
    identifier: name
    properties:
      name:
        type: string
        default: "Banner"
      text:
        type: string
        default: "This is a banner!"
      order:
        type: integer
        default: 0
      display:
        type: boolean
        default: true
banner_exempt_groups:
  type: list
  list_type: group
  default: ""
banner_include_groups:
  type: list
  list_type: group
  default: ""
