banner_delay:
  type: integer
  default: 6000
banner_outlet:
  default: "above-main-container"
banner_text:
  type: list
  default: |
    This is banner 1!
    |This is banner two.
    |This is the third banner.
banner_exempt_groups:
  type: list
  list_type: group
  default: ""
banner_include_groups:
  type: list
  list_type: group
  default: ""
